# Generated by Django 4.2.2 on 2024-01-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('author', models.CharField(max_length=128, verbose_name='Автор')),
                ('genre', models.CharField(max_length=56, verbose_name='Жанр')),
                ('cost', models.CharField(max_length=128, verbose_name='Цена')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
            ],
        ),
    ]
