# Generated by Django 4.2.2 on 2024-01-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_rename_name_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
