# Generated by Django 4.2.2 on 2024-01-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_alter_book_cover_alter_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(height_field=200, null=True, upload_to='files/covers/', verbose_name='Обложка', width_field=140),
        ),
    ]
